from __future__ import annotations

SCHEMA_VERSION = "review-workflow-v2"

CANDIDATE_HEADERS = [
    "citation_id",
    "search_batch",
    "database_source",
    "source_provider",
    "access_mode",
    "retrieval_date",
    "title",
    "authors",
    "year",
    "venue",
    "doi_or_link",
    "document_type",
    "thesis_type",
    "degree_level",
    "granting_institution",
    "advisor",
    "institution_filter",
    "study_or_evidence_hint",
    "topic_tag",
    "duplicate_status",
    "full_text_available",
    "title_abstract_relevance",
    "initial_screen_decision",
    "exclusion_reason",
    "notes",
]

ABSTRACT_SCREEN_HEADERS = [
    "citation_id",
    "screen_round",
    "database_source",
    "topic_tag",
    "enter_full_text_stage",
    "relevance_grade",
    "inclusion_criteria_hit",
    "exclusion_criteria_hit",
    "decision_reason",
    "screened_at",
    "screener",
    "notes",
]

FULLTEXT_ACQUISITION_HEADERS = [
    "citation_id",
    "acquisition_status",
    "acquisition_source",
    "access_mode",
    "authorized_session_used",
    "target_url",
    "acquired_at",
    "version_note",
    "copyright_or_license_note",
    "access_notes",
    "pdf_status",
    "local_filename",
    "readable",
    "is_complete_full_text",
    "has_abstract",
    "paywalled",
    "notes",
]

FULLTEXT_SCREEN_HEADERS = [
    "citation_id",
    "core_question",
    "included",
    "grade",
    "study_or_evidence_role",
    "major_reason",
    "exclusion_reason",
    "full_text_quality",
    "bias_or_quality_assessment",
    "chapter_destination",
    "screened_at",
    "screener",
    "notes",
]

FULLTEXT_REVIEW_HEADERS = [
    "citation_id",
    "review_status",
    "priority",
    "core_question",
    "study_or_evidence_role",
    "is_core_reading",
    "enters_evidence_extraction",
    "bias_or_quality_assessment",
    "key_takeaway",
    "relationship_to_main_claim",
    "limitations",
    "contradictions",
    "notes",
]

EVIDENCE_HEADERS = [
    "citation_id",
    "title",
    "year",
    "venue",
    "source",
    "source_provider",
    "access_mode",
    "thesis_type",
    "degree_level",
    "granting_institution",
    "advisor",
    "study_type",
    "design",
    "question_or_objective",
    "sample_or_data_scale",
    "data_or_material_source",
    "core_metrics_or_outcomes",
    "key_finding",
    "strengths",
    "limitations",
    "bias_or_quality_assessment",
    "evidence_strength",
    "contradiction_point",
    "manuscript_role",
    "chapter_destination",
    "trace_back_page_table_figure_section",
]

PROJECT_DEFAULT_PATHS = {
    "candidate_csv": "02_candidate_pool_and_screening/candidate_pool.csv",
    "abstract_screen_csv": "02_candidate_pool_and_screening/title_abstract_screening.csv",
    "fulltext_acquisition_csv": "03_fulltext_acquisition_and_review/fulltext_acquisition.csv",
    "fulltext_screen_csv": "03_fulltext_acquisition_and_review/fulltext_screening.csv",
    "fulltext_review_csv": "03_fulltext_acquisition_and_review/fulltext_review_register.csv",
    "evidence_csv": "04_evidence_extraction/evidence_extraction.csv",
    "visual_summary_md": "05_writing_and_figure_planning/visual_evidence_pack.md",
    "gate_report_md": "08_revision_and_final_checks/gate_report.md",
}
