#!/usr/bin/env python3
"""Static preflight scan for manuscript drafting residue.

This script scans text-like manuscript files for explicit AI residue,
placeholders, unresolved citations, Markdown/LaTeX artifacts, and common
submission-risk phrases.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path
from typing import Iterable, List, Tuple

SCRIPT_VERSION = "0.2.2"
SUPPORTED_EXTENSIONS = {".txt", ".md", ".tex", ".bib", ".ris"}
OPTIONAL_EXTENSIONS = {".docx", ".pdf"}

PATTERNS: List[Tuple[str, str, str]] = [
    (
        "BLOCKER",
        "explicit_ai_residue",
        r"\b(as an AI language model|generated by (?:ChatGPT|Claude|Gemini|an? AI(?: system| model)?)|AI-generated response)\b",
    ),
    ("BLOCKER", "avoid_ai_detection_residue", r"\b(avoid AI detection|humanize this|make it undetectable|bypass detector)\b"),
    ("MAJOR", "placeholder", r"(TODO|TBD|FIXME|\[insert citation\]|\[add reference\]|\[figure here\]|待补充|请核实|占位)"),
    ("MAJOR", "unresolved_latex", r"(\\cite\{|\\ref\{|\\label\{|\?\?)"),
    ("MAJOR", "markdown_artifact", r"(^```|^#{1,6}\s+|\|\s*---\s*\|)"),
    ("MAJOR", "agent_instruction_residue", r"\b(system prompt|developer message|user prompt|rewrite the following|revise the following)\b"),
    ("MAJOR", "editorial_instruction", r"\b(revise this|polish this|make this more scientific|expand this paragraph|needs citation)\b"),
    ("MINOR", "ai_style_risk", r"\b(delves? into|multifaceted|plays a pivotal role|it is important to note|underscore[s]?|crucial)\b"),
    ("MINOR", "overclaim_risk", r"\b(first|novel|unique|unprecedented|groundbreaking|paradigm-shifting)\b"),
]


def read_text(path: Path) -> str:
    suffix = path.suffix.lower()
    if suffix in SUPPORTED_EXTENSIONS:
        return path.read_text(encoding="utf-8", errors="replace")

    if suffix == ".docx":
        try:
            import docx  # type: ignore
        except Exception as exc:  # pragma: no cover
            raise RuntimeError("python-docx is required for .docx files") from exc
        doc = docx.Document(str(path))
        return "\n".join(p.text for p in doc.paragraphs)

    if suffix == ".pdf":
        try:
            import fitz  # type: ignore
        except Exception as exc:  # pragma: no cover
            raise RuntimeError("PyMuPDF is required for .pdf files") from exc
        parts = []
        with fitz.open(str(path)) as pdf:
            for page in pdf:
                parts.append(page.get_text())
        return "\n".join(parts)

    raise RuntimeError(f"Unsupported extension: {suffix}")


def iter_files(root: Path) -> Iterable[Path]:
    if root.is_file():
        if root.suffix.lower() in SUPPORTED_EXTENSIONS | OPTIONAL_EXTENSIONS:
            yield root
        return
    for path in sorted(root.rglob("*")):
        if path.is_file() and path.suffix.lower() in SUPPORTED_EXTENSIONS | OPTIONAL_EXTENSIONS:
            yield path


def pattern_applies(rule: str, suffix: str) -> bool:
    if rule == "markdown_artifact" and suffix == ".md":
        return False
    return True


def scan_file(path: Path):
    try:
        text = read_text(path)
    except Exception as exc:
        yield {
            "severity": "BLOCKER",
            "rule": "unreadable_file",
            "file": str(path),
            "line": "",
            "match": str(exc),
            "context": "",
        }
        return

    lines = text.splitlines()
    for i, line in enumerate(lines, start=1):
        for severity, rule, pattern in PATTERNS:
            if not pattern_applies(rule, path.suffix.lower()):
                continue
            if re.search(pattern, line, flags=re.IGNORECASE):
                yield {
                    "severity": severity,
                    "rule": rule,
                    "file": str(path),
                    "line": i,
                    "match": re.search(pattern, line, flags=re.IGNORECASE).group(0),
                    "context": line.strip()[:500],
                }


def main() -> int:
    parser = argparse.ArgumentParser(description="Static manuscript residue scan")
    parser.add_argument("target", help="Manuscript file or folder")
    parser.add_argument("--out", default="static_scan.tsv", help="Output TSV file")
    args = parser.parse_args()

    root = Path(args.target)
    rows = []
    fatal_coverage_error = False

    if not root.exists():
        rows.append({
            "severity": "BLOCKER",
            "rule": "input_not_found",
            "file": str(root),
            "line": "",
            "match": "target does not exist",
            "context": "",
        })
        files = []
        fatal_coverage_error = True
    else:
        files = list(iter_files(root))
        if not files:
            rows.append({
                "severity": "BLOCKER",
                "rule": "no_supported_files",
                "file": str(root),
                "line": "",
                "match": "no supported manuscript files found",
                "context": "",
            })
            fatal_coverage_error = True

    for path in files:
        findings = list(scan_file(path))
        rows.extend(findings)
        if any(row["rule"] == "unreadable_file" for row in findings):
            fatal_coverage_error = True

    with open(args.out, "w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=["severity", "rule", "file", "line", "match", "context"], delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)

    print(
        f"scanner={SCRIPT_VERSION}; files={len(files)}; "
        f"findings={len(rows)}; wrote={args.out}"
    )
    if fatal_coverage_error:
        return 2
    return 1 if any(r["severity"] == "BLOCKER" for r in rows) else 0


if __name__ == "__main__":
    sys.exit(main())
